version: "3.7"

services:
  openapi-gen:
    image: openapitools/openapi-generator-cli:v5.4.0
    volumes:
      - ../..:/react-spring
    command: generate -g typescript-fetch -i /react-spring/backend/rest-api-specification/openapi.yaml -o /react-spring/frontend/src/backend/generated-rest-client --additional-properties supportsES6=true,typescriptThreePlus=true
